### ISSUE TITLE
how you managed and of strokes?

### ISSUE THREAD

**Issue by pilot1981** [constgemm/esp_server_activate_gpio#2]
how you managed and of strokes?

**Comment by constgemm** [comment]
I don't seem to understand what you mean. Can you try and rephrase your proposal so that I can grasp the meaning of it? Thank you.
Regards, CG

**Comment by pilot1981** [comment]
How you manage fully close step and fully open step?

**Comment by constgemm** [comment]
The shutter winder itself includes a controller that is set to open and close the blinds fully. At the beginning of the installation the winder is set to stop at the respective end of the winding process. My addition merely imitates the buttons by wiring the relay in a parallel circuit. Pushing the button of the shutter winder controller has the same effect as closing the relay. 
The code therefore doesnt deal with stopping the winding process as that is part of the controller included in the winder. 
Regards, CG
